echo "bashrc loading.."
if [ -f ~/.bashrc.local ]; then
  source ~/.bashrc.local
fi

set -o vi

ulimit -S -n 1024

export EDITOR=vim
export TERM=xterm-color

if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

#source /Users/Nick-Kijak/.config/broot/launcher/bash/br
