if [ -f ~/.bashrc.local ]; then
  source ~/.bashrc.local
fi

set -o vi

ulimit -S -n 1024

export EDITOR=vim
export TERM=xterm-color

export PATH="/home/nkijak/.linuxbrew/bin:/home/nkijak/.linuxbrew/sbin:$PATH"
